default:
  image:
    name: gitlab.itiv.kit.edu:1443/itiv/docker/itiv-rocky8:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
 - pre
 - behav
 - implement
 - postsim
 - post
 - drc
 - upload

behav:i2s_master:
  stage: behav
  script:
    - make i2s_master.sim
  variables:
    LD_PRELOAD: /lib64/libudev.so.1
  artifacts:
    when: always
    paths:
    - out/

behav:sine_generator:
  stage: behav
  script:
    - make sine_generator.sim
  variables:
    LD_PRELOAD: /lib64/libudev.so.1
  artifacts:
    when: always
    paths:
    - out/

behav:clock_generator:
  stage: behav
  script:
    - make clock_generator.sim
  variables:
    LD_PRELOAD: /lib64/libudev.so.1
  artifacts:
    when: always
    paths:
    - out/

behav:zedboard_soc_top:
  stage: behav
  script:
    - make zedboard_soc_top.sim
  variables:
    LD_PRELOAD: /lib64/libudev.so.1
  artifacts:
    when: always
    paths:
    - out/

behav:zedboard_standalone_top:
  stage: behav
  script:
    - make zedboard_standalone_top.sim
  variables:
    LD_PRELOAD: /lib64/libudev.so.1
  artifacts:
    when: always
    paths:
    - out/

implement:zedboard_standalone_top:
  stage: implement
  needs:
   - job: "behav:zedboard_standalone_top"
     artifacts: false
  script:
    - make standalone.bit
  variables:
    LD_PRELOAD: /lib64/libudev.so.1
  artifacts:
    paths:
    - out/

implement:zedboard_soc_top:
  stage: implement
  needs:
   - job: "behav:zedboard_soc_top"
     artifacts: false
  script:
    - make soc.bit
  variables:
    LD_PRELOAD: /lib64/libudev.so.1
  artifacts:
    paths:
    - out/

upload:zedboard_standalone_top:
  stage: upload
  needs:
   - job: "implement:zedboard_standalone_top"
     artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Upload firmware"
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file "out/standalone.bit" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/firmware/${CI_COMMIT_TAG}/standlone.bit"'

upload:zedboard_soc_top:
  stage: upload
  needs:
   - job: "implement:zedboard_soc_top"
     artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Upload firmware"
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file "out/soc.bit" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/firmware/${CI_COMMIT_TAG}/soc.bit"'

pre:sg13g2_soc_top:wrap:
  stage: pre
  image:
    name: docker.io/hpretl/iic-osic-tools:2025.05
    entrypoint: [""]
  script:
    - source /headless/.bashrc && make sg13g2_wrap
  artifacts:
    paths:
    - src/hdl/sg13g2/neorv32_wrap.v

pre:sg13g2_soc_top:sealring:
  stage: pre
  image:
    name: docker.io/hpretl/iic-osic-tools:2025.05
    entrypoint: [""]
  script:
    - source /headless/.bashrc && make sg13g2_sealring
  artifacts:
    paths:
    - script/sg13g2/sealring.gds

behav:sg13g2:blink_led:
  stage: behav
  image:
    name: gitlab.itiv.kit.edu:1443/itiv/docker/rocky9:latest
  needs:
   - job: "pre:sg13g2_soc_top:wrap"
     artifacts: true
  script:
    - source ./script/sg13g2/setup_orfs.sh && source ./script/sg13g2/setup_cocotb.sh && make test_blink_led.sg13g2_sim.rtl
  artifacts:
    when: always
    paths:
    - out/

behav:sg13g2:dac_sin:
  stage: behav
  image:
    name: gitlab.itiv.kit.edu:1443/itiv/docker/rocky9:latest
  needs:
   - job: "pre:sg13g2_soc_top:wrap"
     artifacts: true
  script:
    - source ./script/sg13g2/setup_orfs.sh && source ./script/sg13g2/setup_cocotb.sh && make test_dac_sin.sg13g2_sim.rtl
  artifacts:
    when: always
    paths:
    - out/

behav:sg13g2:mem_quick:
  stage: behav
  image:
    name: gitlab.itiv.kit.edu:1443/itiv/docker/rocky9:latest
  needs:
   - job: "pre:sg13g2_soc_top:wrap"
     artifacts: true
  script:
    - source ./script/sg13g2/setup_orfs.sh && source ./script/sg13g2/setup_cocotb.sh && make test_mem_quick.sg13g2_sim.rtl
  artifacts:
    when: always
    paths:
    - out/

implement:sg13g2_soc_top:
  stage: implement
  needs:
   - job: "pre:sg13g2_soc_top:wrap"
     artifacts: true
   - job: "pre:sg13g2_soc_top:sealring"
     artifacts: true
  image:
    name: docker.io/hpretl/iic-osic-tools:2025.05
    entrypoint: [""]
  script:
    - source /headless/.bashrc && source ./script/sg13g2/setup_orfs.sh && make sg13g2
  artifacts:
    paths:
    - orfs/flow/results/ihp-sg13g2/soc_top

postsim:sg13g2:blink_led:
  stage: postsim
  image:
    name: gitlab.itiv.kit.edu:1443/itiv/docker/rocky9:latest
  needs:
   - job: "implement:sg13g2_soc_top"
     artifacts: true
  script:
    - source ./script/sg13g2/setup_orfs.sh && source ./script/sg13g2/setup_cocotb.sh && make test_blink_led.sg13g2_sim.gl

postsim:sg13g2:dac_sin:
  stage: postsim
  image:
    name: gitlab.itiv.kit.edu:1443/itiv/docker/rocky9:latest
  needs:
   - job: "implement:sg13g2_soc_top"
     artifacts: true
  script:
    - source ./script/sg13g2/setup_orfs.sh && source ./script/sg13g2/setup_cocotb.sh && make test_dac_sin.sg13g2_sim.gl

postsim:sg13g2:mem_quick:
  stage: postsim
  image:
    name: gitlab.itiv.kit.edu:1443/itiv/docker/rocky9:latest
  needs:
   - job: "implement:sg13g2_soc_top"
     artifacts: true
  script:
    - source ./script/sg13g2/setup_orfs.sh && source ./script/sg13g2/setup_cocotb.sh && make test_mem_quick.sg13g2_sim.gl

post:sg13g2_soc_top:fill:
  stage: post
  needs:
   - job: "implement:sg13g2_soc_top"
     artifacts: true
  image:
    name: docker.io/hpretl/iic-osic-tools:2025.05
    entrypoint: [""]
  script:
    - source /headless/.bashrc && source ./script/sg13g2/setup_orfs.sh && make sg13g2_fill
  artifacts:
    paths:
    - orfs/flow/results/ihp-sg13g2/soc_top

drc:sg13g2_soc_top:minimal:
  stage: drc
  needs:
   - job: "post:sg13g2_soc_top:fill"
     artifacts: true
  image:
    name: docker.io/hpretl/iic-osic-tools:2025.05
    entrypoint: [""]
  script:
    - source /headless/.bashrc && source ./script/sg13g2/setup_orfs.sh && make sg13g2_drc
  artifacts:
    when: always
    paths:
    - orfs/flow/results/ihp-sg13g2/soc_top

drc:sg13g2_soc_top:full:
  allow_failure: true
  stage: drc
  needs:
   - job: "post:sg13g2_soc_top:fill"
     artifacts: true
  image:
    name: docker.io/hpretl/iic-osic-tools:2025.05
    entrypoint: [""]
  script:
    - source /headless/.bashrc && source ./script/sg13g2/setup_orfs.sh && make sg13g2_drc_full
  artifacts:
    when: always
    paths:
    - orfs/flow/results/ihp-sg13g2/soc_top

upload:sg13g2_soc_top:
  stage: upload
  needs:
   - job: "implement:sg13g2_soc_top"
     artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Upload GDS"
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file "orfs/flow/results/ihp-sg13g2/soc_top/base/6_1_merged.gds" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/rtl2gds/${CI_COMMIT_TAG}/6_1_merged.gds"'
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file "orfs/flow/results/ihp-sg13g2/soc_top/base/6_final.v" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/rtl2gds/${CI_COMMIT_TAG}/6_final.v"'