variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
 - test
 - bitstream
 - upload

test:i2s_master:
  stage: test
  script:
    - make i2s_master.sim
  artifacts:
    paths:
    - out/

test:sine_generator:
  stage: test
  script:
    - make sine_generator.sim
  artifacts:
    paths:
    - out/

test:clock_generator:
  stage: test
  script:
    - make clock_generator.sim
  artifacts:
    paths:
    - out/

test:fpga_soc_top:
  stage: test
  script:
    - make fpga_soc_top.sim
  artifacts:
    paths:
    - out/

test:fpga_standalone_top:
  stage: test
  script:
    - make fpga_standalone_top.sim
  artifacts:
    paths:
    - out/

bitstream:standalone:
  stage: bitstream
  needs:
   - job: "test:i2s_master"
     artifacts: false
   - job: "test:clock_generator"
     artifacts: false
   - job: "test:sine_generator"
     artifacts: false
   - job: "test:fpga_standalone_top"
     artifacts: false
  script:
    - make standalone.bit
  artifacts:
    paths:
    - out/

bitstream:soc:
  stage: bitstream
  needs:
   - job: "test:clock_generator"
     artifacts: false
   - job: "test:i2s_master"
     artifacts: false
   - job: "test:fpga_soc_top"
     artifacts: false
  script:
    - make soc.bit
  artifacts:
    paths:
    - out/

upload:standalone:
  stage: upload
  needs:
   - job: "bitstream:standalone"
     artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Upload firmware"
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file "out/standalone.bit" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/firmware/${CI_COMMIT_TAG}/standlone.bit"'

upload:soc:
  stage: upload
  needs:
   - job: "bitstream:soc"
     artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Upload firmware"
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file "out/soc.bit" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/firmware/${CI_COMMIT_TAG}/soc.bit"'