implement-standalone:
  stage: test
  script:
    - make standalone.bit
  artifacts:
    paths:
    - out/

implement-soc:
  stage: test
  script:
    - make soc.bit
  artifacts:
    paths:
    - out/

i2s_master_tests:
  stage: test
  script:
    - make i2s_master.sim
  artifacts:
    paths:
    - out/

sine_generator_tests:
  stage: test
  script:
    - make sine_generator.sim
  artifacts:
    paths:
    - out/

clock_generator_tests:
  stage: test
  script:
    - make clock_generator.sim
  artifacts:
    paths:
    - out/