stages:
  - test
  - fpga

implement-standalone:
  stage: fpga
  script:
    - ./ci/fpga_implement.sh implement_standalone
  tags:
    - tools
  artifacts:
    paths:
    - out/

implement-soc:
  stage: fpga
  script:
    - ./ci/fpga_implement.sh implement_soc
  tags:
    - tools
  artifacts:
    paths:
    - out/

i2s_master_tests:
  stage: test
  script:
    - ./ci/run_tests.sh i2s_master_tests
  tags:
    - tools

spi_master_tests:
  stage: test
  script:
    - ./ci/run_tests.sh spi_master_tests
  tags:
    - tools

adau_command_list_tests:
  stage: test
  script:
    - ./ci/run_tests.sh adau_command_list_tests
  tags:
    - tools

sine_generator_tests:
  stage: test
  script:
    - ./ci/run_tests.sh sine_generator_tests
  tags:
    - tools

cpu_ram_tests:
  stage: test
  script:
    - ./ci/run_tests.sh cpu_ram_tests
  tags:
    - tools

cpu_bus_logic_tests:
  stage: test
  script:
    - ./ci/run_tests.sh cpu_bus_logic_tests
  tags:
    - tools
