default:
  image:
    name: gitlab.itiv.kit.edu:1443/itiv/docker/itiv-rocky8

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
 - test
 - software
 - bitstream
 - asic_test
 - asic
 - upload

test:i2s_master:
  stage: test
  needs: []
  script:
    - make i2s_master.sim
  artifacts:
    paths:
    - out/

test:sine_generator:
  stage: test
  needs: []
  script:
    - make sine_generator.sim
  artifacts:
    paths:
    - out/

test:clock_generator:
  stage: test
  needs: []
  script:
    - make clock_generator.sim
  artifacts:
    paths:
    - out/

test:fpga_soc_top:
  stage: test
  needs:
   - job: "test:i2s_master"
     artifacts: false
   - job: "test:clock_generator"
     artifacts: false
  script:
    - make fpga_soc_top.sim
  artifacts:
    paths:
    - out/

test:fpga_standalone_top:
  stage: test
  needs:
   - job: "test:i2s_master"
     artifacts: false
   - job: "test:clock_generator"
     artifacts: false
   - job: "test:sine_generator"
     artifacts: false
  script:
    - make fpga_standalone_top.sim
  artifacts:
    paths:
    - out/

sw:i2s_sin:
  stage: software
  needs: []
  script:
    - make i2s_sin
  dependencies: []
  artifacts:
    paths:
    - out/

sw:i2s_sin_ir:
  stage: software
  needs: []
  script:
    - make i2s_sin_ir
  dependencies: []
  artifacts:
    paths:
    - out/

sw:dac_bit:
  stage: software
  needs: []
  script:
    - make dac_bit
  dependencies: []
  artifacts:
    paths:
    - out/


sw:boardtest:
  stage: software
  needs: []
  script:
    - make boardtest
  dependencies: []
  artifacts:
    paths:
    - out/

behavs:encoder_top:
  stage: asic_test
  needs: []
  script:
    - make encoder_top.xrun
  artifacts:
    paths:
    - out/

behavs:thermometer_encoder:
  stage: asic_test
  needs: []
  script:
    - make thermometer_encoder.xrun
  artifacts:
    paths:
    - out/

syns:encoder_top:
  stage: asic_test
  needs: []
  script:
    - export USER=build && make encoder_top.genus
    - make encoder_top.xrun2
  artifacts:
    paths:
    - out/

syns:thermometer_encoder:
  stage: asic_test
  needs: []
  script:
    - export USER=build && make thermometer_encoder.genus
    - make thermometer_encoder.xrun2
  artifacts:
    paths:
    - out/

imps:encoder_top:
  stage: asic_test
  needs: []
  script:
    - export USER=build && make encoder_top.genus
    - export USER=build && make encoder_top.innovus
    - make encoder_top.xrun3
  artifacts:
    paths:
    - out/


syn:encoder_top:
  stage: asic
  needs: []
  script:
    - export USER=build && make encoder_top.genus
  artifacts:
    paths:
    - out/

syn:thermometer_encoder:
  stage: asic
  needs: []
  script:
    - export USER=build && make thermometer_encoder.genus
  artifacts:
    paths:
    - out/

imp:encoder_top:
  stage: asic
  needs: []
  script:
    - export USER=build && make encoder_top.genus
    - export USER=build && make encoder_top.innovus
  artifacts:
    paths:
    - out/

bitstream:standalone:
  stage: bitstream
  needs:
   - job: "test:fpga_standalone_top"
     artifacts: false
  script:
    - make standalone.bit
  artifacts:
    paths:
    - out/

bitstream:soc:
  stage: bitstream
  needs:
   - job: "test:clock_generator"
     artifacts: false
   - job: "test:i2s_master"
     artifacts: false
   - job: "test:fpga_soc_top"
     artifacts: false
  script:
    - make soc.bit
  artifacts:
    paths:
    - out/

upload:standalone:
  stage: upload
  needs:
   - job: "bitstream:standalone"
     artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Upload firmware"
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file "out/standalone.bit" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/firmware/${CI_COMMIT_TAG}/standlone.bit"'

upload:soc:
  stage: upload
  needs:
   - job: "bitstream:soc"
     artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Upload firmware"
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file "out/soc.bit" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/firmware/${CI_COMMIT_TAG}/soc.bit"'

upload:sw:
  stage: upload
  needs:
   - job: "sw:i2s_sin"
     artifacts: true
   - job: "sw:i2s_sin_ir"
     artifacts: true
   - job: "sw:dac_bit"
     artifacts: true
   - job: "sw:boardtest"
     artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Upload software"
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file "out/i2s_sin.exe.bin" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/firmware/${CI_COMMIT_TAG}/i2s_sin.exe.bin"'
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file "out/i2s_sin_ir.exe.bin" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/firmware/${CI_COMMIT_TAG}/i2s_sin_ir.exe.bin"'
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file "out/dac_bit.exe.bin" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/firmware/${CI_COMMIT_TAG}/dac_bit.exe.bin"'
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file "out/boardtest.exe.bin" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/firmware/${CI_COMMIT_TAG}/boardtest.exe.bin"'
