implement-standalone:
  stage: test
  script:
    - ./ci/fpga_implement.sh implement_standalone
  tags:
    - work1
  artifacts:
    paths:
    - out/

implement-soc:
  stage: test
  script:
    - ./ci/fpga_implement.sh implement_soc
  tags:
    - work1
  artifacts:
    paths:
    - out/

i2s_master_tests:
  stage: test
  script:
    - ./ci/run_tests.sh i2s_master_tests
  tags:
    - work1
  artifacts:
    paths:
    - out/

spi_master_tests:
  stage: test
  script:
    - ./ci/run_tests.sh spi_master_tests
  tags:
    - work1
  artifacts:
    paths:
    - out/

adau_command_list_tests:
  stage: test
  script:
    - ./ci/run_tests.sh adau_command_list_tests
  tags:
    - work1
  artifacts:
    paths:
    - out/

sine_generator_tests:
  stage: test
  script:
    - ./ci/run_tests.sh sine_generator_tests
  tags:
    - work1
  artifacts:
    paths:
    - out/

cpu_ram_tests:
  stage: test
  script:
    - ./ci/run_tests.sh cpu_ram_tests
  tags:
    - work1
  artifacts:
    paths:
    - out/

cpu_bus_logic_tests:
  stage: test
  script:
    - ./ci/run_tests.sh cpu_bus_logic_tests
  tags:
    - work1
  artifacts:
    paths:
    - out/