stages:
  - test
  - bitstream

test:i2s_master:
  stage: test
  script:
    - make i2s_master.sim
  artifacts:
    paths:
    - out/

test:sine_generator:
  stage: test
  script:
    - make sine_generator.sim
  artifacts:
    paths:
    - out/

test:clock_generator:
  stage: test
  script:
    - make clock_generator.sim
  artifacts:
    paths:
    - out/

test:fpga_riscv_top:
  stage: test
  script:
    - make fpga_riscv_top.sim
  artifacts:
    paths:
    - out/

test:fpga_standalone_top:
  stage: test
  script:
    - make fpga_standalone_top.sim
  artifacts:
    paths:
    - out/

bitstream:standalone:
  stage: bitstream
  needs:
   - job: "test:i2s_master"
     artifacts: false
   - job: "test:clock_generator"
     artifacts: false
   - job: "test:sine_generator"
     artifacts: false
#   - job: "test:fpga_standalone_top"
#     artifacts: false
  script:
    - make standalone.bit
  artifacts:
    paths:
    - out/

bistream:soc:
  stage: bitstream
  needs:
   - job: "test:clock_generator"
     artifacts: false
   - job: "test:i2s_master"
     artifacts: false
   - job: "test:fpga_riscv_top"
     artifacts: false
  script:
    - make soc.bit
  artifacts:
    paths:
    - out/