default:
  image:
    name: gitlab.itiv.kit.edu:1443/itiv/docker/itiv-rocky8:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
 - behav
 - implement
 - postsim
 - upload

fpga:i2s_master:
  stage: behav
  script:
    - make i2s_master.sim
  artifacts:
    paths:
    - out/

fpga:sine_generator:
  stage: behav
  script:
    - make sine_generator.sim
  artifacts:
    paths:
    - out/

fpga:clock_generator:
  stage: behav
  script:
    - make clock_generator.sim
  artifacts:
    paths:
    - out/

fpga:zedboard_soc_top:
  stage: behav
  script:
    - make zedboard_soc_top.sim
  artifacts:
    paths:
    - out/

fpga:zedboard_standalone_top:
  stage: behav
  script:
    - make zedboard_standalone_top.sim
  artifacts:
    paths:
    - out/

fpga:standalone:
  stage: implement
  needs:
   - job: "fpga:zedboard_standalone_top"
     artifacts: false
  script:
    - make standalone.bit
  variables:
    LD_PRELOAD: /lib64/libudev.so.1
  artifacts:
    paths:
    - out/

fpga:soc:
  stage: implement
  needs:
   - job: "fpga:zedboard_soc_top"
     artifacts: false
  script:
    - make soc.bit
  variables:
    LD_PRELOAD: /lib64/libudev.so.1
  artifacts:
    paths:
    - out/

upload:fpga_standalone:
  stage: upload
  needs:
   - job: "fpga:standalone"
     artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Upload firmware"
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file "out/standalone.bit" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/firmware/${CI_COMMIT_TAG}/standlone.bit"'

upload:fpga_soc:
  stage: upload
  needs:
   - job: "fpga:soc"
     artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Upload firmware"
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file "out/soc.bit" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/firmware/${CI_COMMIT_TAG}/soc.bit"'

sg13g2:test:
  stage: behav
  script:
    - ./script/sg13g2/setup_orfs.sh && make sg13g2_sim.rtl
  artifacts:
    paths:
    - out/

sg13g2:wrap:
  stage: implement
  image:
    name: docker.io/hpretl/iic-osic-tools:2025.05
  script:
    - make sg13g2_wrap
  artifacts:
    paths:
    - src/hdl/sg13g2/neorv32_wrap.v

sg13g2:rtl2gds:
  stage: implement
  needs:
   - job: "sg13g2:wrap"
     artifacts: true
  image:
    name: docker.io/hpretl/iic-osic-tools:2025.05
  script:
    - ./script/sg13g2/setup_orfs.sh && make sg13g2
  artifacts:
    paths:
    - orfs/flow/results/ihp-sg13g2/soc_top

sg13g2:gl_test:
  stage: postsim
  needs:
   - job: "sg13g2:rtl2gds"
     artifacts: true
  script:
    - ./script/sg13g2/setup_orfs.sh && make sg13g2_sim.gl

upload:sg13g2:
  stage: upload
  needs:
   - job: "sg13g2:rtl2gds"
     artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Upload GDS"
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file "orfs/flow/results/ihp-sg13g2/soc_top/base/6_1_merged.gds" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/rtl2gds/${CI_COMMIT_TAG}/6_1_merged.gds"'
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file "orfs/flow/results/ihp-sg13g2/soc_top/base/6_final.v" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/rtl2gds/${CI_COMMIT_TAG}/6_final.v"'